'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Users',
      [
        {
          firstName: 'Иван',
          lastName: 'Иванов',
          surname: 'Иваныч',
          email: 'Ivan@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Санкт-Петербург',
          position: 'Управляющий прямых продаж',
          department_id: 1,
          role: 'студент',
          course_id: 1,
          receipt_date:'01.09.2023',
          foto: 'https://cs14.pikabu.ru/post_img/2021/11/07/7/163628558219781558.jpg',
          bg_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'student',
          lastName: 'student',
          surname: 'student',
          email: 'student',
          telephone: '11111111',
          password: 'student',
          city: 'Санкт-Петербург',
          position: 'Управляющий прямых продаж',
          department_id: 2,
          role: 'студент',
          course_id: 1,
          receipt_date:'01.09.2023',
          foto: 'https://bipbap.ru/wp-content/uploads/2018/09/800f118d37ec790d8eb5388d68a2d310.jpg',
          bg_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'prepod',
          lastName: 'prepod',
          surname: 'prepod',
          email: 'prepod',
          telephone: '11111111',
          password: 'prepod',
          city: 'Санкт-Петербург',
          position: 'Управляющий прямых продаж',
          department_id: 1,
          role: 'преподаватель',
          course_id: 1,
          receipt_date:'01.09.2023',
          foto: 'https://www.mirf.ru/wp-content/uploads/2021/08/maxresdefault-3.jpg',
          bg_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Петр',
          lastName: 'Петров',
          surname: 'Петрыч',
          email: 'Petr@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Москва',
          position: 'Управляющий торговых сетей',
          department_id: 2,
          role: 'студент',
          course_id: 1,
          receipt_date:'01.09.2023',
          foto: 'https://i.ytimg.com/vi/11a-4Xhrz9Y/sddefault.jpg',
          bg_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Василина',
          lastName: 'Учебникова',
          surname: 'Петровна',
          email: 'Vasilina@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Москва',
          position: 'ЗНСРХ',
          department_id: 1,
          role: 'студент',
          course_id: 1,
          receipt_date:'01.09.2023',
          foto: 'http://s00.yaplakal.com/pics/pics_preview/5/0/9/14124905.jpg',
          bg_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Лебедев',
          lastName: 'Артемий',
          surname: 'Леонидович',
          email: 'Artemiy@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Череповец',
          position: 'Начальник маркетинга',
          department_id: 3,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2022',
          foto: 'https://def4onki.ru/wp-content/uploads/2020/07/maxresdefault-6.jpg',
          bg_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Спящий',
          lastName: 'Дмитрий',
          surname: 'Анатольевич',
          email: 'Dmitriy@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Калининград',
          position: 'ЗНСРХ',
          department_id: 2,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2022',
          foto: 'https://avatars.dzeninfra.ru/get-zen_doc/2957013/pub_61f4165762e8675a96850ed7_61f417072c5367756e020ff7/scale_1200',
          bg_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Говорящий',
          lastName: 'Дмитрий',
          surname: 'Дмитриевич',
          email: 'Dmitriy2@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Москва',
          position: 'Управляющий',
          department_id: 1,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2023',
          foto: 'https://avatars.dzeninfra.ru/get-zen_doc/2408175/pub_60e418542f1be51987b95cc9_60e4189845d24303ec0d4f1e/scale_1200',
          bg_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Аршавин',
          lastName: 'Андрей',
          surname: 'Дмитриевич',
          email: 'Andrey@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Москва',
          position: 'Руководитель группы',
          department_id: 2,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2023',
          foto: 'https://avatars.dzeninfra.ru/get-zen_doc/2408175/pub_60e418542f1be51987b95cc9_60e4189845d24303ec0d4f1e/scale_1200',
          bg_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Главный',
          lastName: 'Сергей',
          surname: 'Семенович',
          email: 'Sergey@sovcombank.ru',
          telephone: '11111111',
          password: '111',
          city: 'Москва',
          position: 'Управляющий',
          department_id: 1,
          role: 'преподаватель',
          course_id: 1,
          receipt_date:'01.09.2023',
          foto: 'https://s0.rbk.ru/v6_top_pics/media/img/9/47/754598824402479.jpeg',
          bg_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Артемов',
          lastName: 'Валентин',
          surname: 'Семенович',
          email: 'ArtemovVS@sovcombank.ru',
          telephone: '+7(960)220-03-22',
          password: 'Артемов',
          city: 'Москва',
          position: 'Управляющий',
          department_id: 1,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2023',
          foto: 'https://thumb.tildacdn.com/tild3635-6565-4136-b037-616631613934/-/resize/744x/-/format/webp/____adobespark.png',
          bg_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Ткаченко',
          lastName: 'Данила',
          surname: 'Семенович',
          email: 'Danila@sovcombank.ru',
          telephone: '+7(960)220-03-22',
          password: 'Артемов',
          city: 'Москва',
          position: 'Управляющий',
          department_id: 1,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2023',
          foto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7J2JfhbBXOi1YprakRfChvYhX_EUybgAuTg&usqp=CAU',
          bg_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Рябов',
          lastName: 'Никита',
          surname: 'Сергеевич',
          email: 'Рябов@sovcombank.ru',
          telephone: '+7(960)220-05-35',
          password: 'Рябов',
          city: 'Москва',
          position: 'Управляющий',
          department_id: 1,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2023',
          foto: 'https://cdn1.tenchat.ru/static/vbc-gostinder/user-picture/c7e5bf3f-ad2c-42bc-a809-40bd8a58974b.jpeg',
          bg_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: 'Камбалова',
          lastName: 'Анна',
          surname: 'Валерьевна',
          email: 'Камбалова@sovcombank.ru',
          telephone: '+7(960)220-05-45',
          password: 'Камбалова',
          city: 'Москва',
          position: 'Управляющий',
          department_id: 1,
          role: 'студент',
          course_id: 2,
          receipt_date:'01.09.2023',
          foto: 'https://plusworld.ru/upload/images/articles/4594-2.jpg',
          bg_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};

